[build]
  command = "npm install --include=optional --include=dev && npm run build --workspace=frontend"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
